version: "3.8"

services:
  frontend:
    build: ./Front_Eval2
    container_name: gestor-user-frontend
    ports:
      - "8080:5000"
    environment:
      BACKEND_URL: http://backend:3000
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./Back_Eval2
    container_name: gestor-user-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: proyecto_db
      DB_PORT: 3306
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    build: ./Data_Eval2
    container_name: gestor-user-db
    command:
      - --innodb-buffer-pool-size=128M
      - --performance-schema=OFF
      - --max-connections=50
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: proyecto_db
    mem_limit: 450m
    memswap_limit: 900m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 61s
    volumes:
      - ./Data_Eval2/01_creacion_base_datos.sql:/docker-entrypoint-initdb.d/01_creacion_base_datos.sql
      - ./Data_Eval2/02_backup_y_mantenimiento.sql:/docker-entrypoint-initdb.d/02_backup_y_mantenimiento.sql
volumes:
  dbdata:
